title: Tulǵa
description: Qaraqalpaq ádebiyatı haqqında
baseurl: ""
url: "https://tulga.uz"

# Jekyll settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  authors:
    output: true
    permalink: /authors/:name/
  works:
    output: true
    permalink: /works/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
